steps:
- name: 'gcr.io/cloud-builders/npm'
  args: ['install']
- name: 'gcr.io/cloud-builders/gcloud'
  args: ['functions', 'deploy', 'toad-alerts', '--trigger-http', '--runtime', 'nodejs10', '--region', 'us-central1', '--entry-point', 'app', '--set-env-vars', 'PIXABAY_API_KEY=$(beta secrets versions access latest --secret=pixabay-api-key)']
  